# Generated by Django 5.0.2 on 2024-03-07 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="휴대전화",
            ),
        ),
    ]
