# Generated by Django 5.0.2 on 2024-03-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth",
            field=models.PositiveIntegerField(null=True, verbose_name="생년월일"),
        ),
    ]
