# Generated by Django 5.0.2 on 2024-03-07 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default="",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format '+123456789'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
