# Generated by Django 5.0.2 on 2024-03-07 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth",
            field=models.CharField(
                default="",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        message="생년월일은 8자리로 표현해야합니다.",
                        regex="^(19[0-9][0-9]|20\\d{2})(0[0-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])$",
                    )
                ],
                verbose_name="생년월일",
            ),
        ),
    ]
