# Generated by Django 5.0.2 on 2024-03-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "장바구니", "verbose_name_plural": "장바구니"},
        ),
        migrations.AddField(
            model_name="cart",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name="cart",
            table="cart",
        ),
    ]
