# Generated by Django 5.0.2 on 2024-03-11 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cart_options_cart_total_price_alter_cart_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="total_price",
            new_name="price",
        ),
    ]
