# Generated by Django 5.0.2 on 2024-03-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="상품명")),
                ("price", models.PositiveIntegerField(verbose_name="가격")),
                ("details", models.CharField(max_length=200, verbose_name="상품설명")),
                ("stock", models.PositiveIntegerField(verbose_name="재고")),
            ],
            options={
                "verbose_name": "상품",
                "verbose_name_plural": "상품",
            },
        ),
    ]
