# Generated by Django 5.0.2 on 2024-03-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("남성", "Men"), ("여성", "Women")],
                max_length=10,
                null=True,
                verbose_name="제품 성별",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="details",
            field=models.TextField(max_length=300, verbose_name="상품설명"),
        ),
        migrations.AlterModelTable(
            name="product",
            table="shop_products",
        ),
    ]
