# Generated by Django 5.0.2 on 2024-03-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_gender_alter_product_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="detail",
            field=models.CharField(max_length=400, null=True, verbose_name="상세정보"),
        ),
    ]
