# Generated by Django 5.0.2 on 2024-03-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_detail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="detail",
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ("xs", "XS"),
                    ("s", "S"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xl", "XL"),
                ],
                max_length=5,
                null=True,
                verbose_name="사이즈",
            ),
        ),
    ]
