# Generated by Django 5.0.2 on 2024-03-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_product_detail_product_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("남성", "Men"), ("여성", "Women")],
                default="",
                max_length=10,
                verbose_name="제품 성별",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ("xs", "XS"),
                    ("s", "S"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xl", "XL"),
                ],
                default="",
                max_length=5,
                verbose_name="사이즈",
            ),
        ),
    ]
