# Generated by Django 5.0.2 on 2024-03-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_gender_alter_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="detail_image1",
            field=models.URLField(default="", verbose_name="상세이미지 1"),
        ),
        migrations.AddField(
            model_name="product",
            name="detail_image2",
            field=models.URLField(default="", verbose_name="상세이미지 2"),
        ),
        migrations.AddField(
            model_name="product",
            name="detail_image3",
            field=models.URLField(default="", verbose_name="상세이미지 3"),
        ),
        migrations.AddField(
            model_name="product",
            name="detail_image4",
            field=models.URLField(default="", verbose_name="상세이미지 4"),
        ),
        migrations.AddField(
            model_name="product",
            name="detail_image5",
            field=models.URLField(default="", verbose_name="상세이미지 5"),
        ),
        migrations.AddField(
            model_name="product",
            name="detail_image6",
            field=models.URLField(default="", verbose_name="상세이미지 6"),
        ),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.URLField(default="", verbose_name="메인 이미지"),
        ),
        migrations.AddField(
            model_name="product",
            name="materials",
            field=models.URLField(default="", verbose_name="소재"),
        ),
        migrations.AddField(
            model_name="product",
            name="size_chart",
            field=models.URLField(default="", verbose_name="사이즈 차트"),
        ),
    ]
