# Generated by Django 5.0.2 on 2024-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_detail_image1_product_detail_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="detail_image1",
            field=models.URLField(blank=True, default="", verbose_name="상세이미지 1"),
        ),
        migrations.AlterField(
            model_name="product",
            name="detail_image2",
            field=models.URLField(blank=True, default="", verbose_name="상세이미지 2"),
        ),
        migrations.AlterField(
            model_name="product",
            name="detail_image3",
            field=models.URLField(blank=True, default="", verbose_name="상세이미지 3"),
        ),
        migrations.AlterField(
            model_name="product",
            name="detail_image4",
            field=models.URLField(blank=True, default="", verbose_name="상세이미지 4"),
        ),
        migrations.AlterField(
            model_name="product",
            name="detail_image5",
            field=models.URLField(blank=True, default="", verbose_name="상세이미지 5"),
        ),
        migrations.AlterField(
            model_name="product",
            name="detail_image6",
            field=models.URLField(blank=True, default="", verbose_name="상세이미지 6"),
        ),
        migrations.AlterField(
            model_name="product",
            name="materials",
            field=models.URLField(blank=True, default="", verbose_name="소재"),
        ),
        migrations.AlterField(
            model_name="product",
            name="size_chart",
            field=models.URLField(blank=True, default="", verbose_name="사이즈 차트"),
        ),
    ]
